name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./MinimalApi/MinimalApi.csproj
    - name: Build
      run: dotnet  build ./MinimalApi/MinimalApi.csproj --no-restore

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:     
    - name: Docker Build & Push Action
  # You may pin to the exact commit or the version.
  # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
    uses: mr-smithers-excellent/docker-build-push@v5.6
    with:
      # Name of the Docker image
      image: 
      # Tags override for Docker image
      tags: # optional
      # Target Docker registry
      registry: dvhd/minimal-api
      # Location of Dockerfile, if not Dockerfile in root directory
      dockerfile: ./MinimalApi/
      # Directory to run `docker build` from, if not project root
      directory: ./MinimalApi/
      # Docker build arguments passed via --build-arg
      buildArgs: # optional
      # Docker build labels passed via --label
      labels: # optional
      # Docker build target passed via --target
      target: # optional
      # Docker registry username
      username: 
      # Docker registry password
      password: 
      # GitHub organization to push image to (if not current)
      gitHubOrg: # optional
      # Adds latest tag to auto-generated GitOps tag
      addLatest: # optional, default is false
      # Suffixes a build timestamp to the branch-based Docker tag
      addTimestamp: # optional, default is false
